export const contenidoEn = {
  locale: 'en',
  metadata: {
    title: 'Cristhian Loor | Backend & Full Stack Developer',
    description:
      'Cristhian Loor’s portfolio: Backend & Full Stack development with Java, Spring Boot, C#, .NET, React, Next.js, and Angular.',
    author: 'Cristhian José Loor Quimí',
    url: 'https://cristhian-loor.vercel.app/en',
    image: 'https://cristhian-loor.vercel.app/social-card.png',
  },
  persona: {
    nombreCompleto: 'Cristhian José Loor Quimí',
    nombreProfesional: 'Cristhian Loor',
    rol: 'Backend & Full Stack Developer',
    ubicacion: 'Guayaquil, Ecuador',
    correo: 'cristhian.loor25@outlook.com',
    github: 'https://github.com/cristhianl10',
    linkedin: 'https://www.linkedin.com/in/cristhian-loor/',
    cv: '/cv-cristhian-loor.pdf',
    idiomas: ['Native Spanish', 'Intermediate English'],
  },
  navegacion: [
    { etiqueta: 'Projects', destino: '#proyectos' },
    { etiqueta: 'Technologies', destino: '#tecnologias' },
    { etiqueta: 'About', destino: '#sobre-mi' },
    { etiqueta: 'Education', destino: '#formacion' },
  ],
  interfaz: {
    saltarContenido: 'Skip to main content',
    irInicio: 'Go to the top',
    abrirMenu: 'Open menu',
    cerrarMenu: 'Close menu',
    menuContacto: 'Contact',
    navegacionPrincipal: 'Main navigation',
    navegacionPie: 'Page links',
    enlacesPrincipales: 'Primary links',
    tecnologias: 'Technologies',
    tecnologiasProyecto: 'Project technologies',
    aspectosDestacados: 'Technical highlights',
    rolesImplementados: 'Implemented roles',
    capas: 'Layers',
    proyectoPresentado: 'Submitted project',
    aspectosInteres: 'Technical interests',
    cambiarAIngles: 'Switch the site to English',
    cambiarAEspanol: 'Switch the site to Spanish',
    activarModoClaro: 'Switch to light mode',
    activarModoOscuro: 'Switch to dark mode',
    proyectoAnterior: 'View previous project',
    proyectoSiguiente: 'View next project',
    seleccionarProyecto: 'Select a project',
    tecnologiasPorProyecto: 'Technologies by project',
    proyecto: 'Project',
    de: 'of',
    abrirNuevaPestana: 'opens in a new tab',
    progresoLectura: 'Reading progress',
    enlacesProyecto: 'Project links',
    verCodigo: 'View code',
    verDemo: 'View demo',
    verDocumentacion: 'View documentation',
    demoProximamente: 'Demo coming soon',
  },
  presentacion: {
    etiqueta: '// BACKEND — FULL STACK',
    titulo: 'Software Engineering student focused on backend.',
    descripcion:
      'Software Engineering student focused on backend development with Java/Spring Boot and C#/.NET. I build REST APIs and full stack applications centered on business logic, architecture, and data management.',
    enfoque:
      'I am particularly interested in software architecture, business logic, databases, and building maintainable solutions.',
    focos: ['Java / Spring Boot', 'C# / .NET', 'Backend / Full Stack'],
    arquitectura: 'Clean Architecture',
    arquitecturaCapas: ['API', 'Application', 'Domain', 'Infrastructure'],
    diseno: 'Repository · Unit of Work',
    disenoDetalles: ['Batch inserts', 'Async processing'],
    pruebas: 'JUnit · xUnit · Jasmine · Postman',
    panel: {
      titulo: 'Technical focus',
      nucleo: 'Backend',
      principales: ['Java / Spring Boot', 'C# / .NET'],
      flujo: ['API', 'Logic', 'Data'],
    },
    capasVisual: ['Business', 'Domain', 'Application', 'API'],
    acciones: {
      proyectos: 'View projects',
      cv: 'Download CV',
      github: 'GitHub',
      linkedin: 'LinkedIn',
    },
  },
  seccionProyectos: {
    etiqueta: '// PROJECTS',
    titulo: 'Projects that show how I build.',
    descripcion:
      'Three real solutions where architecture, business logic, and data management play a central role.',
  },
  proyectos: [
    {
      id: 'ibatch',
      indice: '01',
      nombre: 'iBatch Financial Operations',
      tipo: 'CSV transaction processing',
      reconocimiento: 'Second place at the Hackathon',
      contexto:
        'Built during a Hackathon organized by Universidad Politécnica Salesiana together with ÉPICO Guayaquil.',
      descripcion:
        'A platform that processes CSV files containing financial transactions and tracks processing, validations, progress, and history.',
      tecnologias: ['Java', 'Spring Boot', 'Spring Data JDBC', 'Next.js', 'React', 'MySQL'],
      destacados: [
        'API built with Spring Boot and data access through Spring Data JDBC.',
        'Interface built with Next.js and React.',
        'Asynchronous processing and batch record insertion.',
        'Periodic progress updates and paginated record queries.',
        'Validation of amounts, accounts, and dates.',
        'Error logging and audit history throughout processing.',
      ],
      visual: {
        tipo: 'procesamiento',
        etapas: ['CSV file', 'Validation', 'Processing', 'Audit'],
      },
      enlaces: { repositorio: 'https://github.com/cristhianl10/iBatch', demo: 'https://i-batch.vercel.app', documentacion: 'https://github.com/cristhianl10/iBatch#readme' },
      media: { portada: null, alt: 'iBatch transaction processing diagram', capturas: [] },
    },
    {
      id: 'banco-horizonte',
      indice: '02',
      nombre: 'Banco Horizonte — Claims Management',
      tipo: 'Full stack application',
      descripcion:
        'A full stack platform for managing bank claims end to end. Priority is not assigned in isolation: it comes from business rules that also determine the SLA and shape the subsequent flow.',
      explicacionVisual:
        'Rules accumulate criteria; the resulting priority determines the SLA before the claim continues through a controlled status flow.',
      tecnologias: ['C#', '.NET 10', 'Angular 20', 'PostgreSQL', 'Supabase'],
      arquitectura: ['API', 'Application', 'Domain', 'Infrastructure'],
      destacados: [
        'REST API with .NET and frontend with Angular 20, Angular Signals, and reactive forms.',
        'Clean Architecture with API, Application, Domain, and Infrastructure layers.',
        'Automatic prioritization engine based on cumulative business rules.',
        'Dynamic priority and SLA calculation.',
        'Controlled status flow with validations, complete history, and traceability.',
        'Supabase Auth, JWT authentication, and role-based authorization.',
        'Backend unit tests with xUnit and frontend tests with Jasmine/Karma.',
      ],
      roles: ['Operator', 'Analyst', 'Supervisor', 'Administrator'],
      visual: {
        tipo: 'priorizacion',
        etapas: ['Claim', 'Cumulative rules', 'Priority', 'SLA', 'Status flow', 'Traceability'],
      },
      enlaces: { repositorio: 'https://github.com/cristhianl10/banco-horizonte-reclamos', demo: 'https://banco-horizonte-reclamos.vercel.app', documentacion: 'https://github.com/cristhianl10/banco-horizonte-reclamos/tree/main/docs' },
      media: { portada: null, alt: 'Bank claims workflow diagram', capturas: [] },
    },
    {
      id: 'pos-api',
      indice: '03',
      nombre: 'POS API',
      tipo: 'Backend for a point-of-sale system',
      descripcion:
        'Backend for a point-of-sale system built as a REST API. Its value lies in the backend structure and the use of patterns to keep responsibilities separate.',
      tecnologias: ['C#', '.NET', 'Entity Framework', 'SQL Server', 'REST API'],
      arquitectura: ['API', 'Application', 'Domain', 'Infrastructure'],
      destacados: [
        'Layered organization: API, Application, Domain, and Infrastructure.',
        'Data access through Entity Framework.',
        'Repository Pattern and Unit of Work implementation.',
        'Separation of responsibilities across backend layers.',
        'REST API endpoints tested via HTTP requests.',
      ],
      visual: {
        tipo: 'capas',
        etapas: ['API', 'Application', 'Domain', 'Infrastructure'],
      },
      enlaces: { repositorio: null, demo: null, documentacion: null },
    },
  ],
  tecnologias: {
    etiqueta: '// STACK',
    titulo: 'Technologies applied in context.',
    introduccion:
      'Skills are organized by their role in a solution and connected to the projects where they were applied.',
    categorias: [
      { id: 'backend', nombre: 'Backend', items: ['Java', 'Spring Boot', 'C#', '.NET', 'REST APIs', 'Entity Framework'] },
      { id: 'frontend', nombre: 'Frontend', items: ['JavaScript', 'React', 'Next.js', 'Angular', 'HTML', 'CSS'] },
      { id: 'datos', nombre: 'Databases', items: ['PostgreSQL', 'MySQL', 'SQL Server', 'Oracle SQL', 'Supabase'] },
      { id: 'arquitectura', nombre: 'Architecture and practices', items: ['Clean Architecture', 'SOLID', 'Repository Pattern', 'Unit of Work', 'Separation of responsibilities'] },
      { id: 'testing', nombre: 'Testing', items: ['xUnit', 'Jasmine/Karma'] },
      { id: 'herramientas', nombre: 'Tools and infrastructure', items: ['Git', 'GitHub', 'Docker', 'Linux', 'Postman'] },
    ],
    porProyecto: [
      { nombre: 'iBatch', items: ['Java', 'Spring Boot', 'Spring Data JDBC', 'Next.js', 'React', 'MySQL'] },
      { nombre: 'Banco Horizonte', items: ['C#', '.NET 10', 'Angular 20', 'PostgreSQL', 'Supabase'] },
      { nombre: 'POS API', items: ['C#', '.NET', 'Entity Framework', 'SQL Server'] },
    ],
    relacionTitulo: 'Technologies connected to real projects',
  },
  metodologia: {
    panelEtiqueta: 'From problem to solution',
    panelTitulo: 'Decisions in context',
    panelDescripcion: 'I define the rules, organize responsibilities, and check the main scenarios. I document decisions to make the next change easier to understand.',
    etiqueta: '// METHODOLOGY',
    titulo: 'How I build.',
    pasos: [
      { numero: '01', titulo: 'Understand the problem', texto: 'I identify the context and model the rules the solution must follow.' },
      { numero: '02', titulo: 'Separate responsibilities', texto: 'I design the data model and distribute logic across clear layers.' },
      { numero: '03', titulo: 'Implement and validate', texto: 'I build critical cases and check their main scenarios.' },
      { numero: '04', titulo: 'Test and prepare', texto: 'I document decisions, test the solution, and prepare its deployment.' },
    ],
  },
  reconocimiento: {
    titulo: 'Second place',
    evento: 'Universidad Politécnica Salesiana × ÉPICO Guayaquil Hackathon',
    proyecto: 'iBatch Financial Operations',
    descripcion:
      'The submitted project was a platform for processing CSV files with financial transactions, validations, progress tracking, and audit history.',
  },
  sobreMi: {
    etiqueta: '// PROFILE',
    titulo: 'Software beyond the interface.',
    parrafos: [
      'I am a Software Engineering student at Universidad de Guayaquil. I am interested in understanding software beyond its interface: its architecture, business logic, data, and responsibilities.',
      'I complement backend development with frontend and UX to understand the complete product. I am looking to keep growing professionally through real projects and technical challenges.',
    ],
    aspectos: ['Software architecture', 'Business logic', 'Data management', 'Separation of responsibilities'],
  },
  formacion: {
    titulo: 'Journey and education.',
    programa: 'Software Engineering',
    institucion: 'Universidad de Guayaquil',
    periodo: 'October 2023 — Present',
    estado: 'Currently pursuing a Software Engineering degree.',
    idiomasTitulo: 'Languages',
    etiqueta: '// JOURNEY',
    hitos: [
      { titulo: '2nd place · UPS × ÉPICO Hackathon', descripcion: 'Recognition earned with iBatch Financial Operations.' },
      { titulo: 'Tech Lab UG', descripcion: 'Hands-on work with GNU/Linux and a local web server.' },
      { titulo: 'ÉPICO Sales School', descripcion: 'Additional training in communication, sales, and product.' },
    ],
  },
  contacto: {
    etiqueta: '// CONTACT',
    titulo: 'Professional contact',
    descripcion:
      'Explore my repositories, view my professional profile, or reach me directly by email.',
    correoEtiqueta: 'Email',
    ubicacionEtiqueta: 'Location',
  },
  pie: {
    descripcion: 'Backend & Full Stack Developer · Guayaquil, Ecuador',
    volver: 'Back to top',
    marca: 'CRISTHIAN',
    cta: 'Write to me',
    derechos: '© 2026 Cristhian Loor — All rights reserved',
  },
};
